name: pet_pulse
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Firebase
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9
  
  # AI & ML
  google_ml_kit: ^0.16.0 # Wrapper for ML Kit
  google_generative_ai: ^0.2.0 # For Gemini API
  
  # Monetization
  purchases_flutter: ^6.0.0 # RevenueCat
  
  # Navigation
  go_router: ^13.0.0
  
  # UI & Assets
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  flutter_svg: ^2.0.9
  
  # Utilities
  http: ^1.1.2
  intl: ^0.19.0
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  flutter_markdown: ^0.6.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
